[workspace]
channels = ["conda-forge", "bioconda"]
name = "ncbi_query"
platforms = ["osx-arm64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]
get_info_one_species = {cmd = "python scripts/fetch_biosample.py --genus Tilletia --num-samples 10 --output tests/tilletia.csv"}
summarise_bioprojects = {cmd = "python scripts/summary_bioprojects.py --csv-file tests/tilletia.csv --prefix tests/tilletia"}

# Same workflow as above, but looping through lists of genera
# You can specify the list of genera you wish to search, as well as the number of queries to return. Here, 7. If left blank, then no limit
get_info_species_list = {cmd = "bash scripts/ncbi_query_multiple_genera.sh tests/example_genera.txt 7"}

[dependencies]
python = ">=3.14.3,<3.15"
requests = ">=2.33.0,<3"
pandas = ">=3.0.2,<4"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
ncbi-datasets-cli = ">=18.22.1,<19"
